=== bellmit/memo/xml/msg_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.fangdd.com/newhouse/dc/msg_handle"
	xmlns:tns="http://www.fangdd.com/newhouse/dc/msg_handle"
	elementFormDefault="qualified">

	<attribute name="name" type="string" />
	<attribute name="type" type="string" />
	<attribute name="valid" type="string" />

	<element name="field">
		<complexType>
			<attribute ref="tns:name" use="required" />
			<attribute ref="tns:type" use="required" />
			<attribute ref="tns:valid" use="optional" />
		</complexType>
	</element>

	<element name="validate">
		<complexType>
			<sequence>
				<element ref="tns:field" maxOccurs="unbounded" minOccurs="0"></element>
			</sequence>
		</complexType>
	</element>

	<element name="msg">
		<complexType>
			<sequence>
				<element ref="tns:validate"></element>
				<element name="persistent"></element>
				<element name="handles"></element>
			</sequence>
		</complexType>
	</element>

</schema>

=== bellmit/memo/xml/record_msg.xml
<?xml version="1.0" encoding="UTF-8"?>
<mg:msg xmlns:mg="http://www.fangdd.com/newhouse/dc/msg_handle"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fangdd.com/newhouse/dc/msg_handle msg_schema.xsd">
	<mg:validate>
		<mg:field mg:name="assistant_id" mg:type="int" />
		<mg:field mg:name="city_id" mg:type="int" />
		<mg:field mg:name="company_id" mg:type="int" />
		<mg:field mg:name="store_id" mg:type="int" />
		<mg:field mg:name="agent_id" mg:type="int" />
		<mg:field mg:name="project_id" mg:type="int" />
		<mg:field mg:name="time" mg:type="string" />
	</mg:validate>
	<mg:persistent></mg:persistent>
	<mg:handles></mg:handles>
</mg:msg>
